[deps]
Chron = "68885b1f-77b5-52a7-b2e7-6a8014c56b98"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatGeochem = "df4de05a-b714-11e8-3c2a-c30fb13e804c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
